#!/bin/sh

### BEGIN INIT INFO
# Provides: ocsp
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start daemon at boot time
# Description: Enable service provided by daemon.
### END INIT INFO

case "$1" in
  start)
    start-stop-daemon -m --pidfile /var/run/ocsp.pid --start -b --exec /root/ocsp.sh
    ;;
  stop)
    start-stop-daemon --pidfile /var/run/ocsp.pid --stop
    ;;
  restart)
    "$0" stop
    "$0" start
    ;;
esac
